### PR TITLE
docs: Update docs for firmware v4.5.8 and v4.5.9.

### PR DESCRIPTION
**Pull request by kwagyeman**

### CODE REVIEW

**Comment by kwagyeman** [comment]
@iabdalkader - Docs update PR. The previous docs update commit wasn't merged.

**Comment by iabdalkader** [comment]
Do you need to update the docs for AprilTags ? Also the current firmware is 4.5.9.

**Comment by kwagyeman** [comment]
This PR includes the commits for v4.5.8 and v4.5.9. So, both are required. The live/released docs include both commits.

**Comment by iabdalkader** [comment]
Please send a PR to update the submodule.

**Pull request merged**
