### PR TITLE
Kwabena/set for faster clock

### PR DESCRIPTION
**Pull request by kwagyeman**
This doesn't increase the qspi flash speed though. That has to be done in the bootloader. This just updates the code in MicroPython. Updating this without updating the bootloader has no detrimental effects.

### CODE REVIEW

**Comment by iabdalkader** [comment]
This is the FCB block, there are two of them one for the SBL firmware (generated by the cmd tools), and one for the main firmware. The FCB for the bootloader should be set to 133MHz.

It sounds like the main firmware is reloading the FCB after the jump, does this change fix the speed or not ? 

PS: please reword the first commit to "ports/mimxrt: Make flash clock frequency configurable."

**Comment by kwagyeman** [comment]
No, this fix doesn't change the speed. Was looking for where the FCB block is generated before but couldn't find it. Will need to learn more about how that is made.

**Comment by kwagyeman** [comment]
Digging into this more. The setting is changed in the FCB block. However, the DCD block I think needs to be setup as the clock source for the qspi is maxed out. Need to compare to the bootloader.

**Comment by kwagyeman** [comment]
No progress on this. On debugging:

The firmware appears to be running with a 480 MHz PLL * 18 / 12 -> 720 MHz / 7 -> 102 Mhz for QSPI.
The clock setting it should apply is 480 MHz PLL * 18 / 33 -> 261.8181 MHz / 2 -> 130.909 MHz
 
I can see the bootloader however is running at 480 MHz * 18 / 13 -> 664.61 MHz / 5 -> 132.92 MHz (maybe slower -  I see like 128 MHz on the scope so I'm guessing it's slightly higher).

I see code in the bootloader that appears to apply settings from the FCB block to the QSPI flash. However, changing values in the FCB block makes no difference. The bootloader appears to all all the code required to increase the clock speed of the PLLs to achieve the target flash speed. So... not sure what's going on. From the looks of things though... I think the bootloader needs to be the one to apply the settings change and changing the FCB block should have done that.

**Comment by kwagyeman** [comment]
Figured it out. The bootloader needs to be patched with a really simple change: https://github.com/openmv/openmv_rt_bootloader/pull/2

After the bootloader is patched this PR applies the right serial clock frequency.

**Pull request merged**
