### PR TITLE
ports/mimxrt/OPENMV_RT1060: Disable I2S code.

### PR DESCRIPTION
**Pull request by kwagyeman**
Not relevant for the board.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Okay, but please fix the commit message.

**Comment by kwagyeman** [comment]
Isn't the commit message correct? "ports/OPENMV_RT1060: Disable I2S code."

**Comment by iabdalkader** [comment]
> Isn't the commit message correct? "ports/OPENMV_RT1060: Disable I2S code."

No, `OPENMV_RT1060` is not a port, `mimxrt` is.

**Comment by iabdalkader** [comment]
> > Isn't the commit message correct? "ports/OPENMV_RT1060: Disable I2S code."
> 
> No, `OPENMV_RT1060` is not a port, `mimxrt` is.

Also, does the firmware build without this code ? This port is not very good at disabling things.

**Comment by kwagyeman** [comment]
Gotcha, yeah, it builds. I tested that of-course.

Fixing the commit message now.

**Pull request merged**
