### PR TITLE
Fix for non-functioning UARTs in MP1.9.2

### PR DESCRIPTION
**Pull request by chrisy**
- The UART HAL moved to using "pin" definitions for UART ports.
  That means the _TX and _RX macros for each UART need to be
  defined in terms of pin_XX values. This impacts both UART1 and 3.
- The alternate function for USART1 was missing from pins PB14/15
  in the chip definition file. This may need to be fixed upstream
  also. Without it, the HAL does not allow the function to be
  enabled.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Hi, we're still on MP 1.9 not 1.9.2
I'm going to update to 1.9.2 soon (before the next release) and will revisit this PR.

**Comment by chrisy** [comment]
I may have misread the version number then (I probably got it from the latest update email!); regardless, this patch is needed on the HEAD of your micropython:openmv branch for working UARTs.

**Comment by iabdalkader** [comment]
You've read the number right, I was going to update to latest but decided to update to 1.9 first.

**Comment by iabdalkader** [comment]
We're on MP 1.9.2 now. Thanks for the PR.

**Pull request merged**
