### PR TITLE
ports/mimxrt: Add machine.CAN driver.

### PR DESCRIPTION
**Pull request by kwagyeman**
Adds support for CAN to the IMXRT line of MCUs. It mimics the PYB.CAN module. So, porting python code to it should be very easy.

Compile has been verified for all platforms and the code has been run through uncrustify.

FD Can support is not implemented. While our RT1062 supports FDCAN the interface we need to use is not available on the external GPIO pins on the OpenMV Cam RT10602.

Finally, CAN support is not available on the RT10XX line so there's no edits for those boards.

### CODE REVIEW

**Comment by kwagyeman** [comment]
Wait, it doesn't compile on boards that don't have CAN. Fixing this.

**Comment by kwagyeman** [comment]
Fixed.

**Comment by iabdalkader** [comment]
If this is not going to be merged upstream, at least not any time soon, should we change just our board to make it easier to maintain ?

**Comment by kwagyeman** [comment]
That makes sense. So, drop all the code for other boards?

**Comment by iabdalkader** [comment]
Yes if there's not going to be any progress upstream with CAN API, less code to maintain.

We have some time until the next release, so we can wait and see.

**Comment by kwagyeman** [comment]
It's reduced now.

**Comment by iabdalkader** [comment]
I merged this in https://github.com/openmv/micropython/commit/59b60d5fc60c4233e94f7f14f865c609e59ea34d

Because it needed some fixes.

**Pull request closed without merging**
